# Generated by Django 5.2.9 on 2026-01-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='ai_response',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user_message',
            field=models.TextField(default=''),
        ),
    ]
