# Generated by Django 5.2.9 on 2026-01-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_file_alter_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
    ]
