# Generated by Django 5.2.9 on 2026-01-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_conversation_summary_conversation_total_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
